### ISSUE TITLE
compiling without admin privileges?

### ISSUE THREAD

**Issue by andrewcorrigan** [wjakob/nanogui#1]
I'd really like to try this out.   I did git clone --recursive, configured with cmake.  When I build, it fails when it tries to install into /usr/local.  I don't have admin privileges, and even if I did wouldn't want to install into /usr/local.  Modifying  CMAKE_INSTALL_PREFIX has no effect.

```
[  6%] Performing install step for 'glfw_p'
[100%] Built target glfw
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/GLFW
CMake Error at cmake_install.cmake:31 (file):
  file INSTALL cannot make directory "/usr/local/include/GLFW": No such file
  or directory
```

**Comment by wjakob** [comment]
sorry for the inconvenience. I'm using nanogui in another project, where it is referenced as a CMake subproject like so
```
include(ExternalProject)
set(CMAKE_EXTERNAL_ARGUMENTS -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_GENERATOR=${CMAKE_GENERATOR} -Wno-dev
  -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/ext_build/dist)

ExternalProject_Add(nanogui_p
  URL             "${CMAKE_SOURCE_DIR}/ext/nanogui"
  PREFIX          "ext_build"
  CMAKE_ARGS      ${CMAKE_EXTERNAL_ARGUMENTS}
)
```

That way, all build products get installed into the ext_build/dist folder of the master project.

I think you could also get it to work if you delete all build products /CMake files and call cmake again, but with -DCMAKE_INSTALL_PREFIX on the command line rather than changing that attribute after the initial configuration (where subprojects are already set up).

**Comment by wjakob** [comment]
this is now addressed by the latest commit, where you can specify whether or not to install the project in cmake.

**Comment by andrewcorrigan** [comment]
It just works now.  It looks really nice too :+1: Thank you.
