### ISSUE TITLE
Python bindings for Vector{2i,2f,Xf}

### ISSUE THREAD

**Issue by mrzv** [wjakob/nanogui#131]
I'm tempted to add constructors to the `Vector`s that take `std::tuple` or `std::vector` (the latter in the case of `VectorXf`). Then I'd like to add implicit conversions, like `py::implicitly_convertible<std::tuple<int,int>,Vector2i>()`. Before I do this, I wanted to check if you find such additions reasonable. The main motivation is that I get tired of wrapping values in `Vector2i` when passing them to various functions.

On a tangentially related note, should the constructor for `Vector2f` be `py::init<float,float>`, rather than `py::init<int,int>`?

**Comment by svenevs** [comment]
I don't know how you would do it with `std::vector`, but if that's possible I think that might be effective.  If it is possible to wrap in say a numpy array, that would be excellent.  These are more of requests, not suggestions...

**Comment by mrzv** [comment]
I haven't thought it through, but I don't have anything fancy in mind. `std::vector<float>` would only be used in `VectorXf` constructor — that seems straightforward. And then adding `py::implicitly_convertible<std::vector<float>,VectorXf>()`. Would this work?

**Comment by wjakob** [comment]
> I'm tempted to add constructors to the Vectors that take std::tuple or std::vector (the latter in the case of VectorXf). Then I'd like to add implicit conversions, like py::implicitly_convertible<std::tuple<int,int>,Vector2i>(). Before I do this, I wanted to check if you find such additions reasonable.

Yes, this sounds perfectly reasonable. Rather than pulling in STL for this, I would suggest to accept a ``py::list l`` and then check that ``py::len(l)`` has the right size before calling ``l[0].cast<int>()`` etc. The ``py::implicitly_convertible`` would then take ``py::list`` as the first argment.

The main motivation is that I get tired of wrapping values in Vector2i when passing them to various functions.

> On a tangentially related note, should the constructor for Vector2f be py::init<float,float>, rather than py::init<int,int>?

Yes, it should accept floats. Ints will be implicitly converted.
