### ISSUE TITLE
Support for SDL2

### ISSUE THREAD

**Issue by Lusito** [wjakob/nanogui#138]
I've just come across this library a couple of days in search for a nice UI library, but since the project I'm working on at this moment is using SDL, I couldn't use this in this form.
I know there is an SDL fork already: https://github.com/dalerank/nanogui-sdl
But that fork seems to be a bit out of date and using a weird include path (include files directly in "include", not in "include/nanogui".

Anyway, I thought it'd be easier to maintain if it was just a compile-time flag to set and build straight into the original nanogui.
To do this, I've separated the glfw window code from Screen into WindowBackend.
There is still some work to do. Particularly on the Python side and HDPI code possibly (don't have one of them).
I'd also like to make it so you can set the screen of the window manually, even hide/remove the screen without hiding the window (for games, where the ui is not visible at all times).

Current state can be found here:
https://github.com/Lusito/nanogui

Let me know what you think.
I'm currently working on this with mingw-w64 on windows. Will give clang & gcc on linux a shot soon.

**Comment by wjakob** [comment]
Dear Lusito,

I won’t merge any patches which try to strip or abstract out GLFW (I find it vastly superior to any of the other toolkits). However, please feel free to fork the library to maintain a separate SDL version.

Best,
Wenzel

**Comment by Lusito** [comment]
Why not? GLFW would still be the default. It wouldn't even have a performance impact or anything. I like GLFW more too, but there are projects which already use SDL2, which won't be able to use this library.

**Comment by wjakob** [comment]
That’s fine, these projects can use a fork of this repository. The goal of nanogui is to be “nano” and forkable rather than integrate ever possible feature or framework.

**Comment by tony** [comment]
I'm kind of sad it's a "fork" and not something that could be potentially abstracted. I think it gives people who need SDL2 out of *necessity* (rather than preference) a worry they'll be upkeeping a project that goes out of date from this project. And this is a real awesome one.

The thing is at the present time I can't find a solution in SDL2 that gives me anything resembling what this project does.

@wjakob Have we exhausted the possibility that abstracting out the framework (glfw, sdl2) would bloat nanogui too much? The thing is I'm encountering forks that add SDL2 support for gui libs all the time and they are lacking manpower (https://github.com/wheybags/guichan, https://github.com/billyquith/GWork). Please understand I'm not trying to shift burden on this project in anyway, just striking the note there's a lack of concentration in the area and there's possibility nanogui could scratch more itches beyond glfw, but efforts at forking have been repeatedly going stale with other gui libs.

@Lusito @dalerank, what do you think?  Are you still interested in the project? I think it would be possible to create an SDL2 nanogui fork, but it really depends on demand and maintainers 

One of the things I see missing in https://github.com/dalerank/nanogui-sdl is the pybind11 stuff seems missing.

**Comment by Lusito** [comment]
@tony Honestly, I deleted the fork. I don't have the time to maintain my own fork. Contributing to another project is a whole different story than maintaining your own fork.
The project I needed it for took another route due to wjakobs decision, so at the moment for me there is no reason to pursue this anymore.

Aside from this, I've had many compiling issues with nanogui due to having "warnings as errors" turned on in the project (nanogui spits out warnings like there is no end in sight).

If I ever had to go for another gui library again, I'd write my own (possibly based on nanovg) in clean c++ >=11, maybe using the backend system of [nuklear](https://github.com/vurtun/nuklear/tree/master/demo) as an inspiration (not the immediate mode stuff, that sucks for bigger UIs).

**Comment by tony** [comment]
I'm really just considering using glfw and nanogui without SDL2 for my immediate needs then. The code is just too good.  Besides it's an opportunity to to interact more with a new framework (glfw, I only used SDL2 so far), and pybind11.

nuklear looks *gorgeous*.

I guess if there isn't at least a few willing maintainers for SDL2 stuff, it's probably best to use normal nanogui. I think it's good to know of anyone else shows interest though
