### ISSUE TITLE
Question about GLFramebuffer and ImageView

### ISSUE THREAD

**Issue by saedrna** [wjakob/nanogui#176]
Hi,

I have found nanogui a very lightweight and beautiful GUI lib and I would like to implement a feature using it.

I have drawn something to a ```GLFramebuffer``` and have successful blit it to screen. And I would like to bind the ```mColor``` (I have derived GLFramebuffer to get access to those variables) buffer to the ImageView, but no success.

Would you please give me some hint on how to do this?

Thanks.

Han

**Comment by svenevs** [comment]
I might be misunderstanding you, but I think you want to use the recently added [GLCanvas](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__GLCanvas.html#class-nanogui-GLCanvas) widget.  I believe that is the only widget that you can have that level of direct OpenGL control with.  The [fourth example](https://github.com/wjakob/nanogui/blob/master/src/example4.cpp) shows how to use it.

I don't think the ImageView widget could work with the frame buffer unless you stored it to a texture every time it changed, I'm looking at the [draw method starting here](https://github.com/wjakob/nanogui/blob/master/src/imageview.cpp#L307).  But, you could also just do exactly that?

Hope that helps some, or at least inspires a different idea.  Maybe derive ImageView as well and make your GLFrameBuffer derivative class and this ImageView `friend` classes if you are feeling bold?  You could just override the draw method and point to the framebuffer fields there instead of the textures?

**Comment by saedrna** [comment]
Hi @svenevs 

I don't think the ImageView widget could work with the frame buffer unless you stored it to a texture every time it changed, I'm looking at the draw method starting here. But, you could also just do exactly that?

I think you are partially right with this. I have figured out what is the problem. In glutil.h GLFramebuffer uses render buffer instead of Texture2D object, and ImageView uses the texture object. I have created another FBO wrapper, which uses texture instead of render buffer, and have successfully bind it to ImageView.

**Comment by svenevs** [comment]
Oh yeah that's definitely the right thing to do here.  I must confess I generally only use FBOs with one purpose -- (relatively minimalist) deferred rendering that will always end up being the final result displayed to the screen.  So the first time I saw this class I saw the RenderBuffer stuff, looked up what it was online, and then happily ignored it from then on...

It sounds like it would be easy to have your FBO class inherit from the original (`GLFramebufferTex` or something), giving other users the ability to use textures if they need it?

**Comment by saedrna** [comment]
I think current GLFramebuffer is already good enough, because in most times render buffer is enough and even more efficient for the purpose of blit function.  And for the user who are interested in how to do this, just overload ```GLFramebuffer::init``` by 

```
    mSize = size;
    mSamples = nSamples;

    glGenFramebuffers(1, &mFramebuffer);
    glBindFramebuffer(GL_FRAMEBUFFER, mFramebuffer);

    glGenTextures(1, &mColor);
    glBindTexture(GL_TEXTURE_2D, mColor);

    glTexParameteri(...)

    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, mSize.x(). mSize.y(), 0, GL_RGBA, GL_UNSIGNED_BYTES, 0);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, mColor, 0);
    glDrawBuffer(GL_COLOR_ATTACHMENT0);
    glReadBuffer(GL_COLOR_ATTACHMENT0);   
    glBindTexture(GL_TEXTURE_2D, 0);

    glGenTextures(1, &mDepth);
    glBindTexture(GL_TEXTURE_2D, mDepth);

    glTexParameteri(...)

    glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_STENCIL, mSize.x(). mSize.y(), 0, GL_DEPTH24_STENCIL8, GL_UNSIGNED_INT_24_8, 0);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, mDepth, 0);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_TEXTURE_2D, mDepth, 0);
    glBindTexture(GL_TEXTURE_2D, 0);


    GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
    if (status != GL_FRAMEBUFFER_COMPLETE)
        throw std::runtime_error("Could not create framebuffer object!");

    release();

```

**Comment by svenevs** [comment]
I have to agree, FBOs can get insanely complicated.  Trying to support every possible scenario would get unwieldy.  Though you will probably want to update your `free()` method ;)

This issue made me realize that there is actually a huge benefit to textures + FBO though, which is the ability to wield those directly in shaders.  Thanks for the snippet!

**Comment by wjakob** [comment]
Closing this ticket since this is not a nanogui issue.
