### ISSUE TITLE
Compilation Error Ubuntu 14.04

### ISSUE THREAD

**Issue by JBosom** [wjakob/nanogui#22]
Hello,

I followed the instructions to install required packages and cmake but when I try to do "make" (after cmake) I have the following error.

![nanogui_bug-report](https://cloud.githubusercontent.com/assets/11851102/11187526/1255046c-8c87-11e5-973b-9f529e8a0abf.png)

Here is the output of my cmake (just in case it could help).
![nanogui_bug-report_2](https://cloud.githubusercontent.com/assets/11851102/11188533/9ea1ba6a-8c8b-11e5-98e2-060de6188647.png)

I tried my best to solve the problem or to get around it but I failed, sorry.
In any case, thank you for developing this project. That's very cool.
Best regards

**Comment by wjakob** [comment]
is it possible you're on a 32 bit machine? Can you try with a 64 bit compiler?

**Comment by wjakob** [comment]
I guess this library should compile even on a 32 bit compiler ... The issue you reported in pybind11 has been fixed in the meantime, hence the only necessary change was to update the repository link to the latest version.

I'm closing the issue -- feel free to reopen if your issue has not been addressed.
