### ISSUE TITLE
care to explain the unstored new statements?

### ISSUE THREAD

**Issue by lordadamson** [wjakob/nanogui#230]
Hi,
This is not really an issue but I'd like to understand how does that work.
```
/* No need to store a pointer, the data structure will be automatically freed when the parent window is deleted */
    new Label(window, "Push buttons", "sans-bold");
```
I'm really puzzled and I don't understand the comment.

PS: I'm a great fan of nanogui. Wonderful software indeed.

**Comment by svenevs** [comment]
Voodoo magic :wink:

1. Everything that can be added to a `nanogui::Widget` is an instance of `nanogui::Widget` (subclass or not), that's why all of the constructors take a `parent` pointer.
    - So the only time you need to store a pointer is when you want to add children to something.
    - In this case, it's just a label, so there is no reason to explicitly store the pointer.
2. Every `nanogui::Widget` [inherits from `nanogui::Object`](https://github.com/wjakob/nanogui/blob/f9c3b7a2a9fa7f26ef613a11cb0419b4752d0980/include/nanogui/widget.h#L31), the `object.h` and associated ref class is where the majority of the magic is taking place.
3. With the ref counts, when the parent is deleted, the [parent destructor decreases the ref count of its children](https://github.com/wjakob/nanogui/blob/f9c3b7a2a9fa7f26ef613a11cb0419b4752d0980/src/widget.cpp#L32-L37)
4. Alas we reach the final stage, where [`nanogui::Object::decRef`](https://github.com/wjakob/nanogui/blob/f9c3b7a2a9fa7f26ef613a11cb0419b4752d0980/src/common.cpp#L283-L291) (for which the default value of the boolean parameter is `true` -- and I don't actually think there are any explicit `false` calls anywhere [but could be wrong]) will `delete this`.

Ha! Voodoo magic because this was definitely the first time I'd ever seen a _functioning_ `delete this`.

In practice, what it means for you is that you don't need to worry about managing layout / widget memory (which is really convenient).  In all of the example programs, it's just a simple `main` method which creates a `nanogui::Screen` (or subclass) _in scope_ (no pointer, just a direct instance).  This means that by the end of the main method the `nanogui::Screen` object goes out of scope, its destructor is called, and it all ripples through to any widgets you added to that.

In larger programs, you will likely be creating a subclass of `nanogui::Screen` and storing a pointer to it in some way.  This is the **only** thing you would need to `delete` directly.  E.g.

```cpp
class MyScreen : public nanogui::Screen { ... }

class Controller {
public:
    Controller() { mScreen = new MyScreen(...); }
    ~Controller() { delete mScreen;}// here

protected:
    MyScreen mScreen = nullptr;
}
```

and from `// here` all of the widgets you may have added get destroyed when their ref count reaches 0.

**Comment by austensatterlee** [comment]
Out of curiosity, why was nanogui::Object created instead of just using something like std::shared_ptr?

**Comment by lordadamson** [comment]
Okay my mind was blown 😄

**Comment by svenevs** [comment]
@austensatterlee I'm not sure, I'm not the original author.  Using `std::shared_ptr` could achieve the same thing with greater ease for the author of the library, but it comes at somewhat of a burdensome overhead to the user of the library.  Smart pointers are definitely sweet, but in recent experiences I've actually started shying away from them in specific use cases.  Here are my suspicions:

1. Suppose that the parent `Widget` class has a data member `std::vector<std::shared_ptr<Widget>> mChildren`.  Then in order for the `Widget` constructor taking in a (shared) pointer to the parent to add _itself_ to the `parent->mChildren`, the user of nanogui **must** do this on their own.  You can't create a `shared_ptr` during the construction of the child.  This means that the api gets significantly more complicated to use, and users will now have to
    - Create the shared pointer
    - Call some form of `addChild` method
2. Inheriting from [`std::enable_shared_from_this`](http://en.cppreference.com/w/cpp/memory/enable_shared_from_this) does not change this, [this SO answer gives a pretty good explanation](https://stackoverflow.com/a/27706002/3814202)
3. The above two have been my experience, but after getting bad weak pointer errors I just stopped caring in my own codes and got rid of smart pointers.  Assuming there _is_ a solution (I really don't think there is, at least in c++11), the user now has to do `std::make_shared<Label>("Blah", ....)` all over the place.  It's "aesthetically unwieldy"?

Like I said, these are only guesses as to why it went down like this.  They're probably close, but I feign no claims as to understanding the glorious C++ skillz of the original author...

@lordadamson the original author is kind of "mia" right now with real-life obligations.  When he returns to visit the nanogui issues / prs it would be helpful to him to mark this as closed unless you feel like there is a problem, but I've personally tested for memory leaks on nanogui a few different times and to my knowledge there aren't any :upside_down_face:

**Comment by lordadamson** [comment]
Thank you so much @svenevs your answers were very informative and helpful.

**Comment by wjakob** [comment]
I still exist :), but I'm completely swamped with other projects at the moment, hence the radio silence here.

With regards to why ``Object`` exists: it's to alleviate some of the drawbacks of ``std::shared_ptr`` in particular with regards to the pain involving ``std::enable_shared_from_this`` as @svenevs nicely explained. Putting the reference count directly into the objects completely addresses the issue, and this easily done in NanoGUI since almost all classes inherit from a central object (e.g. ``Widget``) in any case. NanoGUI will be used in future versions of my Mitsuba renderer, which uses a similar ``Object`` class as the root of its hierarchy.
