### ISSUE TITLE
Why is GLTexture not an internal type?

### ISSUE THREAD

**Issue by ghost** [wjakob/nanogui#231]
You know the one in example 1.

**Comment by Athomield** [comment]
I'm not 100% sure but I think it's because nanogui is trying to be as much portable as possible to other graphics APIs such as DX11/12 or Vulkan. Making GLTexture an internal class will make nanogui restricted to opengl only. Please correct me if NanoGUI uses opengl internally except through NanoVG.

**Comment by lordadamson** [comment]
I'm not 100% sure myself but I don't think nanoGUI/NanoVG use anything except for openGL.

**Comment by svenevs** [comment]
NanoGUI is pure OpenGL.  The `glutil.h` file has a large number of OpenGL specific things such as `nanogui::GLShader` etc, and there are raw `glDoX` calls in various locations of the framework.

I'd be willing to bet the non-inclusion into the core library comes from one of these:

1. "Oversight" / lack of demand.  The example1 program's use of loading images for a texture is a common, though far from only use of textures in OpenGL.  I don't know the history of what came when, it could very well be that the first example program was written this way with a much more reduced version of the existing API, and simply never got brought back in.
2. The example1 program texture use is convenient, but the [`STB_IMAGE_IMPLEMENTATION`](https://github.com/wjakob/nanogui/blob/1b7e6ed612ce1feb94bfe6c3c7c202fb8499785f/src/example1.cpp#L52) bit may be exactly what the restriction is.  See #179 

I've never looked into the implication of `STB_IMAGE_IMPLEMENTATION`, but incorporating it in the main library may prevent it from being used elsewhere (can only be defined once).  I lean toward this being the ultimate cause, but honestly have no facts to back that up :wink:

**Comment by lordadamson** [comment]
I don't understand why would `STB_IMAGE_IMPLEMENTATION` be a problem. Why would we have issues using it else where? :D If it is already defined we would just use it. Am I right?

**Comment by svenevs** [comment]
Not quite.  STB is one of those "magic" libraries, a similar one is [`tinyobjloader`](https://syoyo.github.io/tinyobjloader/#usage).  I've never actually looked into how the `#define` does what it does, but it's some sort of preprocessor hack.  The reason it becomes a problem is since `NanoVG` is already using STB, and `NanoGUI` is compiling that, it shouldn't be used again else you get the multiple-definition link errors from the above issue.  My understanding is the shared build actually only works because when linking the `NanoGUI` code using it never touches any `NanoVG` code also using STB.  If you promote the class to part of the main library, the story might change.  If you're interested, though, you could try bringing it into the main lib and seeing if you get the same errors.

On an unrelated thought, it would make sense to rename it to `GLImageTexture` or something, possibly with a parent class `GLTexture` that maybe takes in a width, height, and defaults to zeroing (black) out the texture?  The truth is a full-blown `GLTexture` class would have to be much more robust, distinguishing between internal and external image types, type of storage (short, char, float, etc).  So while the `GLImageTexture` is particularly convenient (maybe find a way to call whatever part of `NanoVG` is able to load the image and call that directly?), the parent class would need a lot more thought to be a truly general purpose `GLTexture`.

**Comment by lordadamson** [comment]
Well it's not really that much magic.
Basically that's how the stb_image.h looks like:

```
// declarations;
#ifdef STB_IMAGE_IMPLEMENTATION
// definitions;
#endif
```

so I suppose somewhere in the cmake STB_IMAGE_IMPLEMENTATION is defined when it's not a shared lib. I can't find it though lol

**Comment by lordadamson** [comment]
BTW I did use nanogui as a static lib and I successfully used stb_image with no issues.

**Comment by svenevs** [comment]
> BTW I did use nanogui as a static lib and I successfully used stb_image with no issues.

Sweet!

> Well it's not really that much magic.

It is more complicated than it seems.  It has to do with what happens in source files.  Each `.cpp` is compiled on a separate compilation unit.  At the end, though, things are all merged back into one library.  So in order for this to be officially correct, you would need to make

1. `gl_image_texture.h`
    - specify class interface / signature etc

2. `gl_image_text.cpp`
    - this is the only file that defines `STB_IMAGE_IMPLEMENTATION`, and realistically also the only one that includes the header for that library (as opposed to including it in `gl_image_texture.h`).

If the `gl_image_texture.h` file defines it, and includes it, that's where things can get messy.

**Comment by svenevs** [comment]
Linking to #179 and closing.  More information may show up there (e.g., pull request closing that issue).
