### ISSUE TITLE
Mac Os X dylib not found

### ISSUE THREAD

**Issue by giulio-sefaira** [wjakob/nanogui#251]
Hello there,
I'm trying to compile an open gl app with nanogui lib, but I have issues finding the dynamic library.
```
dyld: Library not loaded: @rpath/libnanogui.dylib
  Referenced from: [...]
  Reason: image not found
```
I have the nanogui.so and libnanogui.dylib under /usr/local/lib and the g++ option includes that path.
Any ideas what I'm doing wrong ?

**Comment by svenevs** [comment]
1. How did `libnanogui.dylib` end up in `/usr/local/lib`?  AKA did you do `make install` or did you manually copy it yourself?

2. How are you trying to compile your other application?  I'm not sure why it says "image" not found.  I've never seen that before...

NanoGUI is designed to be a submodule that compiles with your project.  See the [compilation docs here](http://nanogui.readthedocs.io/en/latest/compilation.html).

**Comment by giulio-sefaira** [comment]
I called make install

**Comment by svenevs** [comment]
Ok, well the first thing that sticks out is you should **only** have a `.dylib`.  `.so` is for Linux, the only `.so` libraries generated are for the python bindings.  On a fresh installation from master, my mac gave me:

1. `libnanogui.dylib`
2. `nanogui.cpython-36m-darwin.so` (the `36` is for python 3.6)

If you're using Python, you'll need to make sure your `PYTHONPATH` is setup to include that.  For C++, you'll need to make sure that the library shows up in `LD_LIBRARY_PATH`.  You installed to `/usr/local/lib`, which may or may not already be in `LD_LIBRARY_PATH`.

In the end, NanoGUI doesn't even generate cmake modules for installation, because it is not designed to be used as an installed library.  The issue you are experiencing is because whatever you have done is not configured appropriately, either because your project's cmake doesn't make sense, or the libraries you installed are not visible (environment configuration problem).  Without more information, there's no way to help you.

And realistically, the encouraged answer here is to follow the approach described in the documentation using NanoGUI as a submodule.

**Comment by Leafl** [comment]
Even after following @darrenmothersele's https://github.com/wjakob/nanogui/issues/47 it seems that I am still having trouble. (I'm new to using OpenGL, GLFW, GLEW). I've also followed these directions: http://jody-lu-blog.logdown.com/posts/1533525. I'm using Xcode (which may be part of the issue), but does it matter where the project is located with respect to the nanogui and/or nanogui-test directory and nanogui/build or /nanogui-test/build?
I'm also getting the same error and have followed the http://nanogui.readthedocs.io/en/latest/compilation.html but do not entirely understand the Default Configurations.

Also sorry if this is not in the correct thread I am very fairly new to using github, as well as using Cmake, OpenGL, GLFW, GLEW.

**Comment by svenevs** [comment]
Hi @Leafl,

Sorry to hear you're getting turned around.  Some of the things you linked to may have been adding to the confusion.

1. OpenGL is not a full-fledged "API", it's a "contract".  The driver developers (e.g., AMD, NVIDIA, Apple for OSX) provide the actual implementation.
2. Something called the OpenGL "context" needs to be initialized.  Users have many options, for which GLFW, GLEW, and SDL are common choices.  You may also see FreeGLUT floating around on the net.  NanoGUI **used** to use GLEW, but now it uses GLFW.  The issues you linked to were before the switch.  Only one can be used.  So you can't use GLFW and SDL at the same time, or at least doing so is a really bad idea.
3. As the user of NanoGUI, you should happily be able to ignore these details (the purpose of NanoGUI, among other things, is to sweep these details under the rug for you).

The discussion in #267 is about the fact that *currently* NanoGUI and XCode do not work together.  This is an XCode bug, for which a proposed fix is implemented (but needs some cleanup).

AKA at this time, using the `master` branch of NanoGUI, you cannot use XCode.  However, if you are willing to just *not* use XCode, you can build from your terminal using Makefiles.  This is the default action for OSX when using a terminal:

```bash
# Let's just build on the desktop for now
$ cd ~/Desktop

$ git clone --recursive https://github.com/wjakob/nanogui.git
$ cd nanogui

# With CMake, always build "out of source"
$ mkdir build
$ cd build
$ cmake ..

# CMake just generated a `Makefile`, use `ls` to confirm
# This will build NanoGUI
$ make -j 4
```

None of this relates to using NanoGUI in your project, this is just building it.  To get NanoGUI to work with your project, you need to setup a `git submodule`.  That's what Darren's [example repository](https://github.com/darrenmothersele/nanogui-test) is demonstrating.  He put it in a `lib/` folder, so the way you get it there is

```bash
$ cd /path/to/your/reop
$ mkdir lib
$ cd lib/
$ git submodule add https://github.com/wjakob/nanogui.git
```

It's a "link" to a new repository, more information on [submodules here](https://git-scm.com/book/en/v2/Git-Tools-Submodules).  Since he put it in a `lib/` folder, this is why his top-level `CMakeLists.txt` is doing [this](https://github.com/darrenmothersele/nanogui-test/blob/8235ada8a7266a46002e8fa3edcc17586f38b5d9/CMakeLists.txt#L6-L9).

Try getting NanoGUI to build on its own first.  When you are comfortable with that, then setup the `git submodule`.

I hope this has been clear, getting started on this can be a little overwhelming if you're new to OpenGL, CMake, and `git` :scream:
