### ISSUE TITLE
screen without window decoration

### ISSUE THREAD

**Issue by ambitslix** [wjakob/nanogui#253]
Hello,

Is there a way make the Screen have no decorations? Obviously this works with fullscreen=true, however I'd like to remove decorations on a windowed mode, that's smaller then the actual screen res. 

Thanks, Mark

**Comment by svenevs** [comment]
Not directly, but you should be able to do yourself (?)  It works for fullscreen because that's the GLFW default action.  All you need to do is set the window hint **before** creating the `nanogui::Screen`:

```cpp
glfwWindowHint(GLFW_DECORATED, 0);
```

When the explicit `nanogui::Screen` constructor is called, [these lines control the behavior](https://github.com/wjakob/nanogui/blob/17492d3d406713f637209ada1b625a25eb90e528/src/screen.cpp#L108-L123).  Most are direct consequences of the `nanogui::Screen` constructor arguments, except for visibility and using a core GL profile.

So basically, anything that is not explicitly being set in the above linked code you can set yourself [from all of these options](http://www.glfw.org/docs/latest/window_guide.html#window_hints).  If I remember correctly, if you set something that the `nanogui::Screen` constructor also sets, the latest one wins (AKA whatever NanoGUI set).

Hope that works!

P.S. If you `#include <nanogui/opengl.h>` that'll bring GLFW in for you.  You want to let NanoGUI do the first `#include` of GLFW because of [these lines](https://github.com/wjakob/nanogui/blob/c0334597bbd7986ec980ff90476c950cd8bb5299/include/nanogui/opengl.h#L19-L31)

**Comment by ambitslix** [comment]
Thank you,

After reading the glfw docs I was doing: 
		
glfwWindowHint(GLFW_DECORATED, GL_FALSE);

but after the window was created, so it's wasn't working, but now it does. I'm wondering why is this not part of your API?
