### ISSUE TITLE
Hiding the cursor

### ISSUE THREAD

**Issue by glaslos** [wjakob/nanogui#254]
TLDR; I'm trying to hide the cursor in my Python app.
The app runs on an embedded device on a small touch screen. The only interaction I'm interested in is `mouseButtonEvent` (i.e. someone tapping on the screen in any location). This works fine but I end up with a mouse cursor on my app which I would like to hide. Seems like the way would be using this function http://www.glfw.org/docs/3.0/group__input.html#gaa92336e173da9c8834558b54ee80563b unfortunately I seem to be unable to access it from the Python bindings. Any hint on getting this to work?

**Comment by wjakob** [comment]
You will have to extend the Python bindings so that you can access this function. (These sorts of custom requirements are unfortunately beyond what we can support here, so you'll have to modify the code.).

**Comment by svenevs** [comment]
@glaslos if you're interested in creating this, the following may be helpful for the full hiding / revealing.  It's a snippet from a fly camera i wrote a long long time ago

```cpp
/* Upon entering fly mode we want to steal the cursor from being able to exit
 * the application (e.g. if the user mouses out of the window entirely and
 * has sloppy / mouse focus or something). Position it in the center to have
 * more meaningful control over the translations.
 *
 * Since we are manually manipulating the position and mode of the mouse,
 * the 'snap_flag' is set to indicate special care is needed.
 *
 * FLY_MODE_{ENTRY, EXIT} are controlled by hitting the space bar,
 */
if((MODE & FlyCameraState::FLY_MODE_ENTRY) == FlyCameraState::FLY_MODE_ENTRY) {
    mFlyMode = true;
    glfwSetCursorPos(mWindow, mHalfWidth + mOffset.x(), mHalfHeight + mOffset.y());
    glfwSetInputMode(mWindow, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
    mSnapFlag = true;
    MODE &= ~FlyCameraState::FLY_MODE_ENTRY;
}
else if((MODE & FlyCameraState::FLY_MODE_EXIT) == FlyCameraState::FLY_MODE_EXIT) {
    glfwSetCursorPos(mWindow, mHalfWidth + mOffset.x(), mHalfHeight + mOffset.y());
    glfwSetInputMode(mWindow, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
    mSnapFlag = true;
    mFlyMode = false;
    MODE &= ~FlyCameraState::FLY_MODE_EXIT;
}
```

Bells and whistles aside, `mWindow` is the `nanogui::Screen`'s internal `GLFWWindow` pointer.  So the path of least resistance would probably be to just add it to `nanogui::Screen`.

So what we would need is some C++ code that just provides simple wrappers to calling

- `glfwSetCursorPos` (may not be necessary, I had to center the cursor on the window so the fly cam didn't snap)
- `glfwSetInputMode`

I suggest doing it in `nanogui::Screen` because creating direct GLFW bindings would be **very** annoying, and you definitely need the `GLFWWindow` pointer.  On the other hand, since the `nanogui::Screen` class is already being bound for Python, you just need to add the relevant `.def` for the new function(s) you create in [`python/widget.cpp`](https://github.com/wjakob/nanogui/blob/master/python/widget.cpp).

Then the last thing you'll need is to add the `GLFW` constants needed for hiding / displaying in [`python/constants.cpp`](https://github.com/wjakob/nanogui/blob/master/python/constants.cpp).

Shouldn't be too bad, I think.  Good luck!  I'd suggest doing the cursor one as well, since hiding the pointer on its own can lead to confusing interactions :wink:

**Comment by glaslos** [comment]
@wjakob totally understandable, I was just hoping I was missing something :)
@svenevs awesome, thanks for the detailed feedback and pointers on how to get started. Much appreciated.
