### ISSUE TITLE
glLineWidth works incorrectly

### ISSUE THREAD

**Issue by Archer-zty** [wjakob/nanogui#278]
Thanks for the project. I have met a problem.
When I test glLineWidth(9.f) on raw glad+glfw, line width is shown as follows:
![1](https://user-images.githubusercontent.com/14086505/32317461-d3d5b766-bfee-11e7-9d15-39fb23d0daa0.png)
But the rotating rectangle only occupies 1 piexl in example1.cpp whatever the parameter is.
Any idea? 
![2](https://user-images.githubusercontent.com/14086505/32317863-55a761d0-bff0-11e7-9ce5-7eb6a5df11b3.png)

line 600 in example1.cpp, I change the code like this
```
/* Draw 2 triangles starting at index 0 */
+glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
+glLineWidth(9.f);
mShader.drawIndexed(GL_TRIANGLES, 0, 2);
+glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
```

**Comment by svenevs** [comment]
I don't have a computer whose driver actually supports `glLineWidth` greater than 1, but as a sanity check -- does `glLineWidth` even apply to drawing triangles?  I truly don't know, I've long since abandoned `glLineWidth` as it's generally poorly supported / cannot be relied on for consistent results.

If it does apply (as opposed to changing the shader to actually be lines and then `mShader.drawIndexed(GL_LINES, 0, /* however many you made */);`), it may be that the underlying NanoVG libraries' [OpenGL state modification](https://github.com/memononen/nanovg#opengl-state-touched-by-the-backend) is interfering?  Perhaps something gets disabled that you need to re-enable or vice versa?

**Comment by wjakob** [comment]
Changing line width is actually a legacy feature. AFAIK OpenGL drivers are are allowed to ignore this value, and some of the machines I work with will do so.

**Comment by svenevs** [comment]
> When I test glLineWidth(9.f) on raw glad+glfw, line width is shown as follows:

@Archer-zty how **exactly** did you initialize the context?  NanoGUI requests an [OpenGL 3.3 forward compatible core profile](https://github.com/wjakob/nanogui/blob/f62ab889aef5732180b510bc58144d7c229c552c/src/screen.cpp#L121-L126).

> Changing line width is actually a legacy feature

So if you want to go with NanoGUI but keep your linewidth stuff, I believe you cannot request forward compatible or core (meaning use the empty screen constructor, [example 3](https://github.com/wjakob/nanogui/blob/master/src/example3.cpp) shows self-managed GLFW).  You may also need to request an older profile altogether?

That said, I vaguely recall NanoVG (underlying widget library) not working if you remove those.

**Comment by Archer-zty** [comment]
@svenevs Thank you for response. I initialize the context with OpenGL 3.3 and even 4.5 but neither works in NanoGUI(However, figure 1 works).

I think I should abandon this function like @wjakob said "Changing line width is actually a legacy feature".
