### ISSUE TITLE
3D Texture breaking when using screen

### ISSUE THREAD

**Issue by CalumMcManus** [wjakob/nanogui#300]
Draw a model with a texture loaded in from stb_image.

After set up a screen to display UI over the 3D world and the textures break.
Example image shows skybox (cubemap) with dagger model. Dagger model texture is now black, cubemap has strange pattern.

![textureissue](https://user-images.githubusercontent.com/7138008/34755451-fb0af29e-f5bb-11e7-92d6-523aa989e4d3.PNG)

**Comment by svenevs** [comment]
Oh no!  These kinds of bugs are never fun to track down :/

1. The first thing I would check is how you are managing OpenGL state, and compare it with [the list of modified OpenGL state by `nanovg`](https://github.com/memononen/nanovg#opengl-state-touched-by-the-backend).  NanoVG is the underlying widget drawing library, and it may be affecting state you are relying on for your textures.  Solution: make sure you are resetting this state in your `Screen::drawContents` method.

    - In particular, you may want to specifically avoid `GL_TEXTURE0` (which is the default) and instead use say `GL_TEXTURE1` (making sure you use [`glActiveTexture`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glActiveTexture.xhtml) before binding your shader / setting uniforms).

2. It's hard to tell from the image, but it seems like the image being loaded may be the actual problem here.  Possible causes might be doing something like loading an RGB texture and treating it as RGBA or BGRA.  I've definitely seen similar artifacts in my own code when using RGB and binding the texture as RGBA.

3. Looking at where the cube face on the right joins the cube face on the left in the above picture, it seems like the texture coordinates on the cube map may not necessarily agree with each other?

Some questions:

a) what color are you expecting the dagger to be?

b) are you porting this code to NanoGUI from something, where it worked previously?

**Comment by CalumMcManus** [comment]
Sorry for not being clearer, if I take out the nanogui stuff (although I have #include <nanogui.h>) it looks normal like this

![textureissue](https://user-images.githubusercontent.com/7138008/34780015-d9b78acc-f619-11e7-9b41-45ed1b941f2e.PNG)

One thing is strange that if I bind using GL_TEXTURE1 I just get a black screen?

**Comment by CalumMcManus** [comment]
I fixed it!

It seems the version of stb_image I was using before nanogui used slightly different parameters for the stbi_load function. As of this version, I must specify the number of components as the last parameter and that fixed it!
