### ISSUE TITLE
Include error for multiple headers

### ISSUE THREAD

**Issue by Nanidato** [wjakob/nanogui#310]
Running on MVS17, I manage to get the headers to compile, but when I attempt to compile Example 3 (https://github.com/wjakob/nanogui/blob/master/src/example3.cpp) in a project currently with GLAD and GLFW previously included+linked, I get errors like the following:

(glUniform1f: identifier is undefined/not found) in glutil.h

(no such file as GL/glcorearb.h) in glfw3.h

What could it be? GLAD and GLFW work as they should with certainty, as they do when I'm running my own program.

**Comment by svenevs** [comment]
> in a project currently with GLAD and GLFW previously included+linked

As in you have done something like `find_package(glfw3)` in your `CMakeLists.txt`?  This is likely the problem, NanoGUI "is" GLFW, and it compiles GLAD manually.  You may be getting conflicting definitions?

Double check that you are following [the Default Configurations](http://nanogui.readthedocs.io/en/latest/compilation.html#default-configurations) as well as the [Required variables exposed](http://nanogui.readthedocs.io/en/latest/compilation.html#required-variables-exposed).

You will need to remove GLFW and GLAD from your build system.  The `NANOGUI_EXTRA_INCS` is what enables GLFW (and GLAD if applicable), and `NANOGUI_EXTRA_DEFS` adds `-DNANOGUI_GLAD` when GLAD is being used.  Lastly, `NANOGUI_EXTRA_LIBS` will include GLAD where applicable.  AKA your build system should "happily ignore" the fact that GLFW / GLAD are actually being used.

That may not be your problem, there have been other VS 2017 issues, but I thought we fixed those.  I think the only thing that doesn't work right now is a static build for VS 2017, but that only affects the example applications (not the library).

**Comment by Nanidato** [comment]
Doing that seems to get example 2 to build (though I had to comment out just this one line in glutil.h, no idea why that works though):
![image](https://user-images.githubusercontent.com/35590234/35938591-6e4b742e-0bfe-11e8-9a93-c3cc9720eec3.png)

However, example 3 still does not work, it complains of unresolved external symbols:
_imp_glClear in function main                    main.obj
_imp_glClearColor in function main           main.obj
_imp_glClearViewport in function main     main.obj

**Comment by Nanidato** [comment]
@svenevs

I triple checked to make sure I wasn't doing anything wrong - I started from scratch, compiled in CMake, set up a git submodule exactly as outlined here: (https://github.com/wjakob/nanogui/issues/251), linked the created GLAD, GLFW, eigen, etc includes in /ext, linked nanogui.lib, and I STILL am getting the same errors. I really don't know what to try at this point.

**Comment by svenevs** [comment]
Hey @Nanidato,

> though I had to comment out just this one line in glutil.h, no idea why that works though

This seems to be a windows issue.  Apparently MSVC will warn about `static_cast<int>(boolean_value)`, try changing it to just set the int manually?

```cpp
int gl_value = value ? 1 : 0;
// call glUniform1i with `gl_value` instead of `(int) value`
```
> linked the created GLAD, GLFW, eigen, etc includes in /ext, linked nanogui.lib, and I STILL am getting the same errors

it's probably something small.  Please post your `CMakeLists.txt` or link me to a repo if it is online.  Paste your `CMakeListst.txt` in a markdown-codeblock like so (starts with three backticks, then `cmake`, paste, then end with three backticks)

    ```cmake
    # ... paste here ...
    ```

I may be getting hung up on the verbiage here, but you shouldn't need to do anything related to `nanogui/ext` (e.g., you do **NOT** specifically `include_directories` there, NanoGUI handles this for you).

**Comment by Nanidato** [comment]
```cmake
# ... set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")

add_subdirectory(lib/nanogui)
include_directories(lib/nanogui/include)
include_directories(${NANOGUI_EXTRA_INCS})
add_definitions(${NANOGUI_EXTRA_DEFS})

add_executable(game game.cpp)

target_link_libraries(game nanogui ${NANOGUI_EXTRA_LIBS}) ...
```

The problem now is that VS complains that nanogui.dll is missing from my computer, when this is how my folder is setup:
![image](https://user-images.githubusercontent.com/35590234/35994286-d00b4574-0cc4-11e8-83b9-cdc2e8b074e3.png)

nanogui is inside lib, and everything builds fine. The problem is that the crash occurs when I run the program, and it spits out that error.

**Comment by Nanidato** [comment]
Hm...tried manual linking, still nothing.

**Comment by svenevs** [comment]
Hey, that's progress right?!  So a couple of things

1. You're doing a 32 bit build.  That shouldn't be causing this problem, but if you can use 64bit that's preferred.  [Getting the 64bit project can be done as shown here](http://nanogui.readthedocs.io/en/latest/compilation.html#compilation).

2. One thing that **may** be going on here is a stale build environment.  When you are changing things like link dependencies etc, it's a good idea to start with a clean build every time until you've got it all setup and just need to re-compile source files.  This may be even more relevant with visual studio projects.  **Did you do a clean build?**  AKA delete the entire `build` directory including the visual studio project, and re-do it.  It can be convenient to use the `cmake --build . --config Release` like the linked docs while sorting this out, instead of having to wait for Visual Studio to load the entire project.

3. The actual problem you are having here is a total Windows-ism.  If I remember correctly, the DLL file needs to be in the same directory as the executable.  Otherwise, it must appear in a default system folder (don't do this for NanoGUI).  I **think** the way you solve this on Windows is by setting the runtime and archive output directories.  My understanding is that CMake recognizes that DLL files need to go where the executables go.  See [this SO answer](https://stackoverflow.com/a/6595001/3814202) for some more information.  I don't actually have access to visual studio right now though, so I don't know if you also have to set it for each of the Release,Debug etc versions.

Hope that helps some :cry:

**Comment by Nanidato** [comment]
@svenevs 

Holy cow, that fixed it. Everything compiles, never been happier to see a widget. I really appreciate you taking the time to help me out!

**Comment by svenevs** [comment]
Woot, glad it works!

In case other people are reading this, (3) above ([setting `CMAKE_*_OUTPUT_DIRECTORY`](https://stackoverflow.com/a/6595001/3814202)) was what solved this for you?

**Comment by Nanidato** [comment]
Yes. Doing that made nanogui.dll appear in the same director as my executable. Even my original problems (the glUniform1i error) went away.

**Comment by xarthurx** [comment]
@svenevs 

Encounter the same issue of `glUniform1i` error on Windows machine.
Might be good to add the fix into to official repo.
