### ISSUE TITLE
nanogui - Debug assertion failed after nanogui::shutdown()

### ISSUE THREAD

**Issue by clehmann-geo** [wjakob/nanogui#334]
Hello, 

I need help with a "Debug assertion failed" error with VS2017 and Win8 64bit. The error happens after the nanogui::shutdown() command. I have put a simplified version of my code below:

```
#include "Viewer.h"

int main(int argc, char* argv[]) {
nanogui::init();
if (passwordalreadystored) { //do something }
else {
// open login window

Screen app{ { 600 / 2, 800 / 2 }, "Login window" };
Window window{ &app, "" };
TextBox  *username = new TextBox(&window);
TextBox  *password = new TextBox(&window);
.... // more widgets

app.performLayout();
app.setVisible(true);
nanogui::mainloop();
nanogui::shutdown();
} //ERROR HAPPENS HERE

// now open main window
nanogui::ref<Viewer> viewer = new Viewer();
viewer->setVisible(true);
nanogui::mainloop();
nanogui::shutdown();
}
```

Is my method of creating a (first) window using nanogui::Screen correct? I assume the error has to do something with freeing memory when nanogui shuts the first window down. For the (second) main window I have used the approach from the examples.

Thanks for help in advance!

**Comment by svenevs** [comment]
The setup leading up to the error looks ok to me.  but you may run into problems if you "init -> mainloop -> shutdown -> mainloop -> shutdown", `mainloop` cannot be run again after `shutdown`.  if you're interested, [`nanogui::init` starts here](https://github.com/wjakob/nanogui/blob/885e4fccc69bbfdd4c527009eef8ed33641d9765/src/common.cpp#L38), the key here being `glfwInit()`.

- i think you either need another call to `nanogui::init()`, or create `viewer` first and keep it invisible (don't call `setVisible(true)` yet, but you are missing a call to `viewer->performLayout()` and should do that).  then find a way (e.g., a simple derived screen class) to get `app` to call `viewer->setVisible(true)` as its closing action, so that `mainloop()` will continue.
- the point: `nanogui::init() ~ glfwInit()` and `nanogui::shutdown() ~ glfwTerminate()`, so you either need another `init()` before the second `mainloop`, or create `viewer` beforehand, even if it is not visible yet

So if you are getting the error at `shutdown()`, it's actually coming from GLFW.  this is a known problem on linux with wayland, but i haven't seen it happen on windows yet.  to update GLFW, try using my "fork" locally as a temporary check.

```console
$ cd /path/to/nanogui/ext/

# i don't remember the windows command for recursive delete...
# but just delete the glfw external dependency folder so you can clone
$ rm -rf glfw

# now clone the fork
$ git clone https://github.com/svenevs/glfw.git
$ cd glfw
$ git checkout upgrade_to_321
```

The `upgrade_to_321` branch has the patches to GLFW's build system rebased on top of GLFW v3.2.1.  This fixes segfault issues for me on Linux / wayland, maybe it will fix your windows issues?

**Note**: you should start with a clean build directory after doing this (delete and start over running `cmake`).

**Comment by clehmann-geo** [comment]
Thanks @svenevs I will give it a try!
