### ISSUE TITLE
Are there any programs released with nanogui?

### ISSUE THREAD

**Issue by hsnks100** [wjakob/nanogui#343]
I play on nanogui nowdays. Suddenly I was wondering if there was a progam with nanogui.

**Comment by svenevs** [comment]
Hi @hsnks100!

Here are a couple:

- InstantMeshes application: https://github.com/wjakob/instant-meshes
- Tev application: https://github.com/Tom94/tev

Not sure exactly what NanoGUI is used for in the product Color Finale, see https://github.com/wjakob/nanogui/pull/245#issuecomment-321655715

Hope you've had success with NanoGUI so far :)

**Comment by gmagno** [comment]
Hej hej,

Thanks for this lovely gui lib!
I was also wondering, are there any projects in Python you could share some references? I have been exploring with nanogui, a bit by looking at the examples, reading the docs, and the C++ source code. So far having a lot of fun :smiley:

![image](https://user-images.githubusercontent.com/46817915/53704886-1b91b700-3dff-11e9-929c-8a4517b80a68.png)

On a different note (should I create a new ticket?), how can I manage timed events? For instance to update the position of a wandering object in the scene. I understand glfw could help with that, but since I am using python, and running the mainloop in detached mode seems to be broken (#335) I am not sure what my options are.

Cheers,
