### ISSUE TITLE
GLFW needs an update

### ISSUE THREAD

**Issue by crazycarl** [wjakob/nanogui#347]
Updating my graphics driver to NVidia's Linux driver version 396.24.02 caused the NanoGUI demos to start crashing, but my own personal projects kept working correctly.

I found the difference was my version of GLFW. Update GLFW in the repository to version 2.3.1 and everything goes back to being just peachy. I tried to figure out how to update the sub-repository in my own fork so I could make a pull request but I'm still pretty new to this.

Are you using this repository as the sub-repository? I'm pretty sure this is the official repository.
https://github.com/glfw/glfw

**Comment by svenevs** [comment]
A resolution to this problem is being actively worked on.  Currently NanoGUI uses a fork of GLFW.  Just wanted to let you know that the issue is known, but the solution is a little harder to solve for reasons specific to how NanoGUI and GLFW currently work with one another.  On linux with NVIDIA drivers you will typically be getting a segfault in `glfwTerminate()`, OSX may produce the same problem depending on the operating system.

**Comment by crazycarl** [comment]
I'm glad a solution is being worked on, although I should note that my case was a bit different from what is described here. My segfault happened on startup.

After updating NanoGUI's GLFW and getting it to work, other issues that I think were caused by the graphics driver showed up in other applications as well. Every other time I closed the game Factorio, my whole system would freeze. I couldn't even get to the virtual terminals. I eventually reverted my graphics driver.

Put it simply, although this issue's solution is the same solution to the other issues, I think this may not actually be a bug in in GLFW/NanoGUI, but rather the more modern version of GLFW has implemented a workaround.

Also, which fork of GLFW are you using? I'm wondering why you went with it and not the official one.

**Comment by svenevs** [comment]
> Put it simply, although this issue's solution is the same solution to the other issues, I think this may not actually be a bug in in GLFW/NanoGUI, but rather the more modern version of GLFW has implemented a workaround.

Oh no. I wouldn't be surprised though, that's often how things go in this realm...

> Also, which fork of GLFW are you using? I'm wondering why you went with it and not the official one.

Sorry, I should have included more information (disclaimer, I am not the author).  He used his own fork, primarily (but not exclusively) to support consumption of the GLFW objects directly.  In CMake, you cannot consume `$<TARGET_OBJECTS:some_lib>` for a `project(...)` declared in a nested scope (from `add_subdirectory`.  So [step 1 is create `glfw_objects`](https://github.com/wjakob/glfw/blob/228b355798fb57dfc97986a5e1f911ede177dedc/src/CMakeLists.txt#L56), followed by this

https://github.com/wjakob/nanogui/blob/885e4fccc69bbfdd4c527009eef8ed33641d9765/CMakeLists.txt#L366

There technically was hope for `$<TARGET_OBJECTS:glfw>` in CMake 3.12, but that got reverted in rc3 because there were serious bugs.  Regardless, relying on 3.12 wouldn't have been a good decision anyway (too new).

Part of the problem is that GLFW's 3.3 release has been at 94% for something like 6 months.  Holding out for 3.3 was nice in theory, as Gandalf would say "[we've / I've] put this off for far too long" xD

**Comment by svenevs** [comment]
Consolidating this issue to #297. It will hopefully be resolved soon.
