### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by 360CodeSafe** [wjakob/nanogui#348]
/ext/nanogui/resources/bin2c.c  line 47

when the function returned in line 48，the memory allocated in line 37 would leak.

**Comment by svenevs** [comment]
Hi @360CodeSafe,

It seems you are inspecting a prtent project that uses NanoGUI based off the path specified. That parent project should probably update their submodule reference to the latest master, NanoGUI used cmake for bin2c now (rather than compile an executable). This should almost certainly alleviate the stated problem.

If not, please provide some more information that we can take action on in this repository.

**Comment by 360CodeSafe** [comment]
OK  i see the update of NanoGUI .
