### ISSUE TITLE
Nanogui as git submodule with existing dependencies

### ISSUE THREAD

**Issue by AndySomogyi** [wjakob/nanogui#361]
Hi @wjakob , 

Is it possible to use nanogui as a git submodule, where I'm already using the nanogui sub-submodules in my project? 

Edit: I've started looking through the nanogui cmake, and I think I can update it to check if there's already an existing glfw and other subproject already configured in the cmake, and if not, try to build it's own.

Question: do you accept pull requests, and assuming I make a few changes to nanogui cmake to get it to work with existing GLFW and other modules, would you accept this change? 

Basically, when GLFW and other modules are built in cmake, these set certain cmake variables, I can have the nanogui cmake check for these vars, and if they're set, just use these existing versions. 

Here's how my repo is structured and my use case: 

Specifically, in my project, already have an GLFW and Eigen, so can I structure the CMake to work like this:

```
myproject/extern
                /glfw
                /eigen
                /nanogui
```

So, here, make nanogui pick up the existing glfw and eigen that I already build, instead if having it's own versions?

**Comment by svenevs** [comment]
Hey @AndySomogyi I've been working on updating CMake for this repo, those changes should be getting submitted for review soon.I want to run the existing bypass plan by you to make sure this is going to support what you need.

Restatement of your goal to make sure I understand: you want to be able to ask NanoGUI to link against a different GLFW that you are building (rather than NanoGUI consuming glfw objects into itself), and/or use a different version of Eigen.

So in the soon to be proposed changes, it will look like this for your project:

```cmake
# You need to make sure that you do this before adding NanoGUI
# ... set any glfw options etc ...
add_subdirectory(extern/glfw)

# ... a `glfw` target has now been defined ...

# ... set any nanogui options and ...
set(NANOGUI_EXTERNAL_GLFW glfw) # the target
add_subdirectory(extern/nanogui)
```

The way it works is that NanoGUI checks `if (DEFINED NANOGUI_EXTERNAL_GLFW)`, then either

1. `if (TARGET ${NANOGUI_EXTERNAL_GLFW})` it will `target_link_libraries` against the provided target (this is your case).
2. Otherwise, if it's defined but not a target, then `find_package(glfw3 CONFIG REQUIRED)` (this is to support the needs of packaging).

Does that make sense / will it work for you?  Eigen will have a similar bypass, but also be allowed to be a directory path (since its header only).

**Comment by svenevs** [comment]
Consolidating this issue to #297. It will hopefully be resolved soon.
