### ISSUE TITLE
Is there a way to show *** in TextBox instead of real text for password usage?

### ISSUE THREAD

**Issue by jialiuBellus3d** [wjakob/nanogui#376]
Thanks

**Comment by svenevs** [comment]
Good question, this will help you get _part_ of the way there, but not all the way.  You'll need to reference the `src/textbox.cpp` implementation pretty heavily, the way `TextBox` works is basically by adding / editing `mValueTemp` while the user is typing (`keyboardCharacterEvent`).  Then when user hits `<enter>` it "commits" the value to `mValue`.

In the below code in `main` I'm abusing the callback a little bit, if you called `TextBox::focusEvent(false)` at the beginning of `PasswordTextBox::focusEvent` then the updates to `mActualValue` will not be available yet.

```cpp
#include <nanogui/label.h>
#include <nanogui/layout.h>
#include <nanogui/screen.h>
#include <nanogui/textbox.h>
#include <nanogui/window.h>

#include <iostream>

class PasswordTextBox : public nanogui::TextBox {
public:
    PasswordTextBox(nanogui::Widget *parent, const std::string &value = "Untitled")
        : nanogui::TextBox(parent, value) { }

    virtual bool focusEvent(bool focused) {
        if (mEditable) {
            if (focused)
                mActualValueTemp = mActualValue;
            else
                mActualValue = mActualValueTemp;
        }

        // calling after above so that callback printout makes things clear
        TextBox::focusEvent(focused);

        return true;
    }


    virtual bool keyboardCharacterEvent(unsigned int codepoint) override {
        // don't call parent keyboardCharacterEvent
        if (mEditable && focused()) {
            std::ostringstream convert;
            convert << (char) codepoint;

            deleteSelection();
            mValueTemp.insert(mCursorPos, "*");
            mActualValueTemp.insert(mCursorPos, convert.str());
            mCursorPos++;

            mValidFormat = (mValueTemp == "") || checkFormat(mValueTemp, mFormat);

            return true;
        }

        return false;
    }

    std::string actual_value() const { return mActualValue; }

protected:
    std::string mActualValue;/// Holds actual password
    std::string mActualValueTemp;
};

int main() {
    nanogui::init();

    {
        auto *screen = new nanogui::Screen({400, 400}, "Password Textbox", false);

        auto *window = new nanogui::Window(screen, "Some Window");
        window->setLayout(new nanogui::GroupLayout());
        window->setSize({300, 300});
        window->setFixedSize({300, 300});
        window->center();

        new nanogui::Label(window, "The Password");
        auto *pass_box = new PasswordTextBox(window, "");
        pass_box->setEditable(true);

        pass_box->setCallback([&](const std::string &s) {
            std::cout << "Callback:\n"
                      << "  s:            " << s << '\n'
                      << "  value:        " << pass_box->value() << '\n'
                      << "  actual_value: " << pass_box->actual_value() << '\n';
            return true;
        });

        screen->performLayout();
        screen->setVisible(true);
        nanogui::mainloop();
    }

    nanogui::shutdown();
    return 0;
}
```

The problem is that `deleteSelection` works directly on `mValueTemp`.  Try running the above code and do in this order:

1. Type `asdf` in text box and hit `<enter>`.
2. Click back at end of text and backspace four times, then type `sss` and hit `<enter>`.

The result of `mActualValue` will be `sssasdf`.  An easy to implement (but pretty hacky) approach is to override `keyboardEvent` as well.  You basically want to copy-paste the whole function from `TextBox`, but with one catch: anywhere you see a call to `deleteSelection()` you need to perform two calls:

```cpp
std::string backup = mValueTemp;
mValueTemp = mActualValueTemp;
deleteSelection();// works directly on mValueTemp

mValueTemp = backup;
deleteSelection();
```

Because now you have two strings that you are manipulating with one cursor.  You'd need the same hack in the code I shared above for `keyboardCharacterEvent` too.

It's not exactly clean, but it should at least work.  Hope that helps some :slightly_smiling_face:

**Comment by jialiuBellus3d** [comment]
@svenevs Thanks for the explanation. I got it working~

I ended up not using the helper function.

What I did is truncate the mActualValueTemp inside keyboardEvent like this

truncate(mActualValueTemp, mCursorPos, (int)(mActualValueTemp.size()-mValueTemp.size()));
